name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"  # triggers on any new git tag

jobs:
  deploy:
    name: Deploy New Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Deploys plugin code + assets to WordPress.org SVN
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          slug: custom-typekit-fonts  # your plugin slug
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
